### ISSUE TITLE
Does not get Http Errors

### ISSUE THREAD

**Issue by Parag2385** [icapps/niddler#10]
First of all, Thank you so much for such an amazing library and tool. It definitely helped me debug HTTP requests & responses. 

But it does not provide anything if API request fails for some reasons such as SocketTimeout or other network issues. 

OkHttp does show these kinds of errors. As this library uses OkHttp is there any way you can show those error responses as well?

Thank you again!

**Comment by NicolaChimerapps** [comment]
Hi,

How are you configuring the niddler okhttp interceptor?

**Comment by Parag2385** [comment]
I'm using Dagger and defining the dependencies in the following way:


        @Singleton
        @JvmStatic
        @Provides
        fun provideNiddler(application: Application): Niddler {
            val niddler = AndroidNiddler.Builder()
                .setPort(0)
                .setNiddlerInformation(AndroidNiddler.fromApplication(application))
                .build()
            niddler.attachToApplication(application)
            return niddler
        }

        @Singleton
        @JvmStatic
        @Provides
        fun provideNiddlerInterceptor(niddler: Niddler): Interceptor {
            return NiddlerOkHttpInterceptor(niddler, "NiddlerInterceptor")
        }

        @Singleton
        @JvmStatic
        @Provides
        fun provideOkHttpClient(mSharedPrefs: SharedPreferences, niddlerInterceptor: Interceptor): OkHttpClient {

            val loggingInterceptor = HttpLoggingInterceptor()
            loggingInterceptor.level = HttpLoggingInterceptor.Level.BODY

            return OkHttpClient.Builder()
                .addInterceptor(AuthInterceptor(mSharedPrefs))
                .connectTimeout(45, TimeUnit.SECONDS)
                .writeTimeout(45, TimeUnit.SECONDS)
                .readTimeout(45, TimeUnit.SECONDS)
                .addInterceptor(niddlerInterceptor)
                .build()
        }


        @JvmStatic
        @Provides
        fun provideRetrofitInstance(client: OkHttpClient): Retrofit {
            return Retrofit.Builder()
                .baseUrl(BASE_URL)
                .addCallAdapterFactory(RxJava2CallAdapterFactory.createWithScheduler(Schedulers.io()))
                .addConverterFactory(ScalarsConverterFactory.create())
                .addConverterFactory(GsonConverterFactory.create())
                .client(client)
                .build()
        }

**Comment by NicolaChimerapps** [comment]
That setup looks correct!

For the timeouts, it kind of makes sense that these responses are not logged in niddler, since there never was any response to log in the first place (as opposed to servers replying with 408 for example).

I tried to come up with an example of how you could implement this behaviour on top of/next to what exists now with the default implementation, but it seems that there is currently no way to do this. I will look into this

**Comment by NicolaChimerapps** [comment]
Version 1.2.0 was released which allows you to configure the OkHttpInterceptor to report downstream exceptions as responses with code 0 and include the stack trace
