### ISSUE TITLE
Integrating with Koin

### ISSUE THREAD

**Issue by Parag2385** [icapps/niddler#17]
This is not an issue, it's just a question. How can I use niddler with Koin for DI. I've used niddler with Dagger2 and it works great, but I'm shifting from Dagger to Koin. Can you describe how can I achieve this? Thanks.

**Comment by NicolaChimerapps** [comment]
Given that niddler is mainly used automatically with OkHttp, just add the niddler initliazing code where you create the OkHttp client with koin.
This depends too much on your own setup to provide an example
