### ISSUE TITLE
Feature idea: option to wait until niddler debugger is attached before letting requests through

### ISSUE THREAD

**Issue by maartenvang** [icapps/niddler#18]
Right now it's impossible to rewrite/debug requests that happen at the startup of your app, because you can't attach the debugger fast enough. It would be nice to have a flag/feature to block the app launch or block all requests until you have attached the niddler debugger.

How Android does it would be really cool: https://user-images.githubusercontent.com/22808988/59292310-d1fd0780-8c4a-11e9-929b-d2a5ff18ee92.png

But without UI this feature would still be very useful, imo.

**Comment by NicolaChimerapps** [comment]
This already exists. You can pass an integer extra to the launch intent (by configuring a new launch configuration in Android studio for example). The option you need to pass is (I think, no access to my pc right now) : `-ei Niddler-Wait-For-Debugger=1`

This should give you exactly what you expect if you use the automatic niddler life cycle watcher (default operation)

**Comment by NicolaChimerapps** [comment]
I checked, it is: `--ei Niddler-Wait-For-Debugger 1`

**Comment by matejdro** [comment]
Could this be documented somewhere?

**Comment by NicolaVerbeeck** [comment]
I have added a section in the readme
