### ISSUE TITLE
Display cache status

### ISSUE THREAD

**Issue by matejdro** [icapps/niddler#19]
When interceptor is added via `OkHttpClientBuilder.addInterceptor` (as opposed to `OkHttpClientBuilder.addNetworkInterceptor`), Niddler will also capture requests that were not actually made to the server, but were just loaded from OKHttp's disk cache.

It would be nice if there was some indicator when request was made from the cache and not from the network.

**Comment by NicolaChimerapps** [comment]
There should be an indication in the UI. Next to the down arrow in timeline mode there should be a special cache icon. This icon shows if the network-response of OkHttp gives HTTP code 304

**Comment by matejdro** [comment]
This only works if OkHttp actually makes a response. If it uses only disk cache (when `max-age` is set and not-stale), then cached response is returned with status code 200.

**Comment by NicolaChimerapps** [comment]
This is a case I did not check, good call. Will investigate!

**Comment by NicolaChimerapps** [comment]
This is pending in plugin: https://github.com/Chimerapps/niddler-ui/pull/29

**Comment by NicolaChimerapps** [comment]
1.4.0 has been released. Plugin update 2.9.9 is pending jetbrains approval

**Comment by matejdro** [comment]
Awesome, thanks a lot!
