### ISSUE TITLE
Niddler does not copy handshake parameter when creating debug response

### ISSUE THREAD

**Issue by matejdro** [icapps/niddler#20]
When Niddler creates a new debug response, it does not copy handshake parameter from the original response.

If niddler is added as network interceptor, this causes OKHttp's cache to crash since they expect this to be non-null on all https responses: https://github.com/square/okhttp/blob/168cbffb6ea28cc0287464baf66e39505e98ae9c/okhttp/src/main/kotlin/okhttp3/Cache.kt#L589

Maybe to avoid issues like this in the future, new request builder could be created with `response.newBuilder()` (if old request exists) call instead of `new Response.Builder()` in the [NiddlerOkHttpInterceptor](https://github.com/icapps/niddler/blob/53b568067cc0e013ed2bfa9586481eca1a0a7b8b/niddler-lib-base/src/main/java/com/icapps/niddler/interceptor/okhttp/NiddlerOkHttpInterceptor.java#L244)?

**Comment by NicolaChimerapps** [comment]
Niddler is not really designed to work as a network interceptor. I will investigate this and see if we can fix this.

**Comment by matejdro** [comment]
There are some benefits to using a network interceptors in some cases, so I think it would be a good idea to support it: https://square.github.io/okhttp/interceptors/#choosing-between-application-and-network-interceptors

**Comment by NicolaChimerapps** [comment]
1.4.0 has been released. Plugin update 2.9.9 is pending jetbrains approval

**Comment by matejdro** [comment]
Awesome, thanks a lot!
